### PR TITLE
Fix pipelinerun logs error

### LINKED ISSUE #998: `tkn pr logs <pr-name>` shows `Error: pipelinerun has not started yet` for a Running pipeline
# Version and Operating System

**tkn Version:**
Latest dev

**Operating System:** 
All

# Expected Behavior
`tkn pr logs <pr-name>` should show the logs for running pipeline

# Actual Behavior
`tkn pr logs <pr-name>` shows `Error: pipelinerun has not started yet` for a Running pipeline

# Steps to Reproduce the Problem

1. Create a pipeline and start the pipeline
2. Make sure that the pipeline starts and `tkn pr logs -f <pr-name>`
3. Once the pipeline run shows the logs run the command `tkn pr logs <pr-name>`

# Additional Info
Below are the command logs

```
$ tkn pr logs -f pipeline-test-run-tsmmb
[run-script : step-one] Hello from Python!
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
[run-script : step-one] this is task
$ tkn pr logs pipeline-test-run-tsmmb
Pipeline still running ...
Error: pipelinerun has not started yet
```

### PR DESCRIPTION
**Pull request by piyush-garg**
This will fix the error of pipelinerun log
which was showing pipelinerun not started
in case of pipelinerun is running

Fix #998

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Fix pipelinerun logs error in case of running pipeline
```

### CODE REVIEW

File: pkg/cmd/pipelinerun/logs_test.go [hunk 1]
```diff
@@ -1948,10 +1948,10 @@ func TestLogs_nologs_v1beta1(t *testing.T) {
 	}
 	prlo := logOptsv1beta1(prName, ns, cs, dc, fake.Streamer([]fake.Log{}), false, false)
 	output, err := fetchLogs(prlo)
-	if err == nil {
-		t.Errorf("Unexpected output: %v", output)
+	if err != nil {
+		t.Errorf("Unexpected error: %v", err)
 	}
-	test.AssertOutput(t, "pipelinerun has not started yet", err.Error())
+	test.AssertOutput(t, "pipelinerun is still running: Running\n", output)
```
Comment (vinamra28) [inline pkg/cmd/pipelinerun/logs_test.go:1954]: just one nit: 
```suggestion
	test.AssertOutput(t, "PipelineRun is still running: Running\n", output)
```
can we address the following issue https://github.com/tektoncd/cli/issues/605 otherwise
/lgtm

File: pkg/log/pipeline_reader.go [hunk 2]
```diff
@@ -234,6 +238,13 @@ func hasPipelineRunFailed(prConditions duckv1beta1.Conditions) error {
 	return nil
 }
 
+func isPipelineRunRunning(prConditions duckv1beta1.Conditions) error {
+	if len(prConditions) != 0 && prConditions[0].Status == corev1.ConditionUnknown {
+		return fmt.Errorf("pipelinerun is still running: %s", prConditions[0].Message)
+	}
+	return nil
+}
+
```
Comment (danielhelfand) [inline pkg/log/pipeline_reader.go:247]: This should probably return a bool. It's not an error if the PipelineRun is still running. We should probably avoid printing to Stderr in this case.

File: pkg/log/pipeline_reader.go [hunk 3]
```diff
@@ -158,8 +158,12 @@ func (r *Reader) waitUntilAvailable(timeout time.Duration) error {
 			}
 		case <-time.After(timeout * time.Second):
 			watchRun.Stop()
+			if err = isPipelineRunRunning(run.Status.Conditions); err != nil {
+				fmt.Fprintln(r.stream.Err, err.Error())
+				return nil
```
Comment (danielhelfand) [inline pkg/log/pipeline_reader.go:163]: Per comment below on returning a bool, instead of printing to Stderr here, the message could just be written to Stdout.

File: pkg/log/pipeline_reader.go [hunk 4]
```diff
@@ -234,6 +238,13 @@ func hasPipelineRunFailed(prConditions duckv1beta1.Conditions) error {
 	return nil
 }
 
+func isPipelineRunRunning(prConditions duckv1beta1.Conditions) error {
+	if len(prConditions) != 0 && prConditions[0].Status == corev1.ConditionUnknown {
+		return fmt.Errorf("pipelinerun is still running: %s", prConditions[0].Message)
```
Comment (danielhelfand) [inline pkg/log/pipeline_reader.go:243]: Please capitalize `PipelineRun` to help with efforts in #605. While it may be odd initially having it lowercase some places, it will eventually all follow this format.

File: pkg/log/pipeline_reader.go (hunk 2 above)
Comment (piyush-garg) [reply pkg/log/pipeline_reader.go:247]: It will be like this `pipelinerun is still running: Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 2, Skipped: 0`

Comment (danielhelfand) [reply pkg/log/pipeline_reader.go:247]: Thanks for the clarification. What you have makes sense to me then.

File: pkg/cmd/pipelinerun/logs_test.go (hunk 1 above)
Comment (piyush-garg) [reply pkg/cmd/pipelinerun/logs_test.go]: addressed

File: pkg/log/pipeline_reader.go (hunk 2 above)
Comment (piyush-garg) [reply pkg/log/pipeline_reader.go]: Thanks, addressed

File: pkg/log/pipeline_reader.go (hunk 4 above)
Comment (piyush-garg) [reply pkg/log/pipeline_reader.go]: addressed

File: pkg/log/pipeline_reader.go (hunk 3 above)
Comment (piyush-garg) [reply pkg/log/pipeline_reader.go]: addressed

**Comment by piyush-garg** [comment]
@danielhelfand @vinamra28 Addressed your comments

**Comment by danielhelfand** [comment]
/lgtm

@VeereshAradhya Any concerns with this?
