### PR TITLE
Avoid Use of Previous TaskRunSpecStatus and PipelineRunSpecStatus with Start Commands

### LINKED ISSUE #1200: Using a cancelled taskrun/pipelinerun for the tag --use-taskrun/--use-pipelinerun sets the status of newly created taskrun/pipelinerun to cancelled
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b3b92b2", GitCommit:"b3b92b2", GitTreeState:"clean", BuildDate:"2020-07-15T09:27:21Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+359dd79", GitCommit:"359dd790a64aa35b626a6a081abddd7db9e2dd37", GitTreeState:"clean", BuildDate:"2020-09-24T13:29:40Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  $ tkn version
  Client version: 0.13.0
  Pipeline version: v0.16.3
  Triggers version: v0.8.1

  ```

- Operating System:

  ```
  All
  ```

# Expected Behavior
The taskrun/pipelinerun should start and completed successfully

# Actual Behavior
The taskrun/pipelinerun status is getting set to `Cancelled`

# Steps to Reproduce the Problem

1. Create a task/pipeline
2. Start the task/pipeline and cancel the taskrun/pipelinerun
3. Start the taskrun/pipelinerun with command using `--use-taskrun`/`--use-pipelinerun` and provide name of cancelled taskrun/pipelinerun

# Additional Info
**Note**: `tkn t/p start task-name/pipeline-name -L` causes the same problem if the last taskrun/pipelinerun status is `cancelled`
**Command execution logs**:
```
$ tkn tr ls
No TaskRuns found
$ 
$ tkn t start wait-task
? Value for param `test-param` of type `string`? check
TaskRun started: wait-task-run-gjd2c

In order to track the TaskRun progress run:
tkn taskrun logs wait-task-run-gjd2c -f -n veeresh-user1
$ 
$ 
$ tkn tr ls
NAME                  STARTED          DURATION   STATUS
wait-task-run-gjd2c   16 seconds ago   ---        Running
$ 
$ tkn tr cancel wait-task-run-gjd2c
TaskRun cancelled: wait-task-run-gjd2c
$ 
$ tkn tr ls
NAME                  STARTED          DURATION     STATUS
wait-task-run-gjd2c   36 seconds ago   28 seconds   Cancelled(TaskRunCancelled)
$ 
$ 
$ tkn t start wait-task --use-taskrun wait-task-run-gjd2c
TaskRun started: wait-task-run-rn285

In order to track the TaskRun progress run:
tkn taskrun logs wait-task-run-rn285 -f -n veeresh-user1
$ 
$ 
$ tkn tr ls
NAME                  STARTED         DURATION     STATUS
wait-task-run-rn285   9 seconds ago   0 seconds    Cancelled(TaskRunCancelled)
wait-task-run-gjd2c   1 minute ago    28 seconds   Cancelled(TaskRunCancelled)
$ 
$ tkn pr ls
No PipelineRuns found
$ 
$ 
$ tkn p start test-cancel-pipeline
? Value for param `test-param-pipeline` of type `string`? check-pipeline
PipelineRun started: test-cancel-pipeline-run-x4j99

In order to track the PipelineRun progress run:
tkn pipelinerun logs test-cancel-pipeline-run-x4j99 -f -n veeresh-user1
$ 
$ tkn pr ls
NAME                             STARTED         DURATION   STATUS
test-cancel-pipeline-run-x4j99   9 seconds ago   ---        Running
$ 
$ 
$ tkn pr cancel test-cancel-pipeline-run-x4j99
PipelineRun cancelled: test-cancel-pipeline-run-x4j99
$ 
$
$ tkn p start test-cancel-pipeline --use-pipelinerun test-cancel-pipeline-run-x4j99
PipelineRun started: test-cancel-pipeline-run-c7r5g

In order to track the PipelineRun progress run:
tkn pipelinerun logs test-cancel-pipeline-run-c7r5g -f -n veeresh-user1
$ 
$ 
$ tkn pr ls
NAME                             STARTED         DURATION     STATUS
test-cancel-pipeline-run-c7r5g   9 seconds ago   0 seconds    Cancelled(PipelineRunCancelled)
test-cancel-pipeline-run-x4j99   1 minute ago    23 seconds   Cancelled(PipelineRunCancelled)

```

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #1200 

In #1134, the method for using previous TaskRun/PipelineRun runtime values as part of a new run was changed to capture the entire TaskRunSpec/PipelineRunSpec. The problem with this is that the Spec for TaskRuns/PipelineRuns contain the TaskRunSpecStatus/PipelineRunSpecStatus, which are used for cancelling runs. 

If `--use-taskrun`/`--use-pipelinerun` or `--last` are passed the name of a cancelled run, the new run will be cancelled. While the choice of having TaskRunSpecStatus/PipelineRunSpecStatus is a bit curious, `tkn` needs to account for this case. The method used in this pr is to save the SpecStatus and reapply it to the run after the previous spec is copied over to avoid factoring this status into the new run's success or failure. 

# Submitter Checklist

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

For pull requests with a release note:

```release-note
Prevent cancelled TaskRuns/PipelineRuns used with --use-pipelinerun/--use-taskrun and --last from being cancelled
```

/kind bug

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow
Thanks @danielhelfand

File: pkg/cmd/pipeline/start.go [hunk 1]
```diff
@@ -254,7 +254,10 @@ func (opt *startOptions) startPipeline(pipelineStart *v1beta1.Pipeline) error {
 			pr.ObjectMeta.GenerateName = usepr.ObjectMeta.Name + "-"
 		}
 		// Copy over spec from last or previous PipelineRun to use same values for this PipelineRun
+		prStatus := pr.Spec.Status
 		pr.Spec = usepr.Spec
+		// Reapply original status in case PipelineRun used was cancelled
+		pr.Spec.Status = prStatus
```
Comment (piyush-garg) [inline pkg/cmd/pipeline/start.go:260]: is there any issue with doing it like

```
pr.Spec = usepr.Spec
pr.Spec.Status = ""
```
Is there any specific reason, to keep the new struct and assign again, as we create the pr struct above only.

File: pkg/options/start.go [hunk 2]
```diff
@@ -91,7 +91,10 @@ func (taskRunOpts *TaskRunOpts) UseTaskRunFrom(tr *v1beta1.TaskRun, cs *cli.Clie
 		tr.ObjectMeta.GenerateName = trUsed.ObjectMeta.Name + "-"
 	}
 	// Copy over spec from last or previous TaskRun to use same values for this TaskRun
+	trStatus := tr.Spec.Status
 	tr.Spec = trUsed.Spec
+	// Reapply original status in case TaskRun used was cancelled
+	tr.Spec.Status = trStatus
```
Comment (piyush-garg) [inline pkg/options/start.go:97]: same as in the case of pipelinerun

**Review by piyush-garg — CHANGES_REQUESTED** [review]

File: pkg/cmd/pipeline/start.go (hunk 1 above)
Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go:260]: Yes, it appears this works fine. Can change it in both cases.

Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go]: Addressed

File: pkg/options/start.go (hunk 2 above)
Comment (danielhelfand) [reply pkg/options/start.go]: Addressed

**Comment by danielhelfand** [comment]
@piyush-garg test for clustertask added
