### PR TITLE
Print message also in case of pipelinerun failure

### LINKED ISSUE #64: Show failure reason when a pipelinerun fails
The `tkn pr describe` command does not include any details when a pipeline run fails:
```
$ tkn pr describe build-pipelinerun-4cp85
Name:              build-pipelinerun-4cp85
Namespace:         pipelines-tutorial
Pipeline Ref:      build-pipeline
Service Account:   pipeline

Status
STARTED          DURATION    STATUS
41 seconds ago   0 seconds   Failed(PipelineInvalidGraph)

Resources
NAME        RESOURCE REF
app-git     petclinic-git
app-image   petclinic-image

Params
No params

Taskruns
No taskrun
```

While this info is available on the status:

```
$ kubectl describe pipelinerun build-pipelinerun-4cp85
...
Status:
  Completion Time:  2019-06-05T13:20:32Z
  Conditions:
    Last Transition Time:  2019-06-05T13:20:32Z
    Message:               PipelineRun pipelines-tutorial/build-pipelinerun-4cp85's Pipeline DAG is invalid: couldn't add link between deploy and build-image: Task deploy depends on build-image but build-image wasn't present in Pipeline
    Reason:                PipelineInvalidGraph
    Status:                False
    Type:                  Succeeded
  Start Time:              2019-06-05T13:20:32Z
Events:                    <none>
```

### PR DESCRIPTION
**Pull request by piyush-garg**
# Changes

While describing a pipeline run also print a message
so that user can see details about the failure in case
of pipeline run failure

Add case for empty message probability

Refactor the function so that
we can leverage the function at multiple places

Fixes #64

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

File: pkg/formatted/k8s.go [hunk 1]
```diff
@@ -22,3 +22,10 @@ func Condition(c apis.Condition) string {
 
 	return status
 }
+
+func IsFailed(c apis.Condition) bool {
```
Comment (sthaha) [inline pkg/formatted/k8s.go]: imho, we shouldn't have functions that are not related to fomatting an input to return a string in this package.

Comment (sthaha) [reply pkg/formatted/k8s.go]: Also. `HasFailed` may improve readability

File: pkg/cmd/pipelinerun/describe.go [hunk 2]
```diff
@@ -97,6 +97,11 @@ func printPipelineRunStatus(w *tabwriter.Writer, pr *v1alpha1.PipelineRun, p cli
 	fmt.Fprintf(w, statusBody, formatted.Age(*pr.Status.StartTime, p.Time()),
 		formatted.Duration(pr.Status.StartTime, pr.Status.CompletionTime),
 		formatted.Condition(pr.Status.Conditions[0]))
+
+	if (formatted.IsFailed(pr.Status.Conditions[0])) {
```
Comment (sthaha) [inline pkg/cmd/pipelinerun/describe.go]: could you please move the function to this package itself; may be calling it `hasFailed` ?

File: pkg/cmd/pipelinerun/describe.go [hunk 3]
```diff
@@ -97,6 +97,11 @@ func printPipelineRunStatus(w *tabwriter.Writer, pr *v1alpha1.PipelineRun, p cli
...
+		fmt.Fprintln(w, "\nMessage")
+		fmt.Fprintln(w, pr.Status.Conditions[0].Message)
```
Comment (hrishin) [inline pkg/cmd/pipelinerun/describe.go]: what if message field is empty?
Is there any probability? :thinking:

File: pkg/cmd/pipelinerun/describe.go [hunk 4]
```diff
@@ -97,6 +99,11 @@ func printPipelineRunStatus(w *tabwriter.Writer, pr *v1alpha1.PipelineRun, p cli
 	fmt.Fprintf(w, statusBody, formatted.Age(*pr.Status.StartTime, p.Time()),
 		formatted.Duration(pr.Status.StartTime, pr.Status.CompletionTime),
 		formatted.Condition(pr.Status.Conditions[0]))
+
+	if (hasFailed(pr.Status.Conditions[0]) && (pr.Status.Conditions[0].Message != "")) {
```
Comment (hrishin) [inline pkg/cmd/pipelinerun/describe.go]: Would it better to have `func hasFailed(pr) (bool, message)` , something like this?
```
func HasFailed(status v1alpha1.PipelineRunStatus) (bool, string) {
	c := status.Conditions[0]
	if c.Status == corev1.ConditionFalse {
		return true, c.Message
	}

	return false, ""
}
```
In this way, it could give a message as well and exactly functionality is also required in pipeline logs case?

File: pkg/cmd/pipelinerun/describe.go (hunk 3 above)
Comment (vdemeester) [reply pkg/cmd/pipelinerun/describe.go]: I feel there is :sweat_smile:

File: pkg/cmd/pipelinerun/describe.go (hunk 4 above)
Comment (vdemeester) [reply pkg/cmd/pipelinerun/describe.go]: Would work I think :angel:

**Comment by hrishin** [comment]
@piyush-garg could you please squash the commits?

**Comment by piyush-garg** [comment]
@hrishin @sthaha Addressed all the comments.
