### PR TITLE
Remove Assertions to Help with Debugging EventListener e2e Failures

### LINKED ISSUE #1206: EventListener Logs e2e Tests Failing
# Expected Behavior

e2e tests associated with EventListener logs should pass.

# Actual Behavior

Tests are failing due to updates in the format of the logs: 

Expecting:
```
{"level":"info","logger":"eventlistener","caller":"eventlistenersink/main.go:98","msg":"Listen and serve on port 8080","knative.dev/controller":"eventlistener"}
```

Actual:
It looks like timestamps for each log line were added in the most recent triggers release, which is causing the [tests' assertions](https://github.com/tektoncd/cli/blob/62784644bb602875ddcbea4667f8b294aa257ec3/test/e2e/eventListener/eventListener_test.go#L58) to fail.

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #1206 

Since EventListener tests rely on `strings.Contains`, getting the diff of failures is a bit more difficult. 

This pull request changes the tests to use a testing utility maintained in `kn` called `ContainsAll`, which checks if many substrings are available in a string.

# Submitter Checklist

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/eventListener/eventListener_test.go [hunk 1]
```diff
@@ -17,13 +17,12 @@ package pipeline
...
 import (
 	"context"
-	"strings"
 	"testing"
 
 	"github.com/tektoncd/cli/test/cli"
 	"github.com/tektoncd/cli/test/framework"
 	"github.com/tektoncd/cli/test/helper"
-	"gotest.tools/v3/assert"
+	"gotest.tools/assert"
```
Comment (sthaha) [inline test/e2e/eventListener/eventListener_test.go:25]: is this change required?

Comment (danielhelfand) [reply test/e2e/eventListener/eventListener_test.go:25]: I'm not sure of all the nuances of it, but there is an error when using `assert.Check` from `gotest.tools/v3/assert`. For what it's worth, `kn` strictly uses `gotest.tools/assert` when using `ContainsAll`.

**Comment by piyush-garg** [comment]
Why the go files are getting created in the license folder

**Comment by danielhelfand** [comment]
> Why the go files are getting created in the license folder

It's part of [`hack/update-deps.sh`](https://github.com/tektoncd/cli/blob/62784644bb602875ddcbea4667f8b294aa257ec3/hack/update-deps.sh#L57).

**Review by piyush-garg — COMMENTED** [review]
/lgtm
