### PR TITLE
ClusterTask start interactive mode

### LINKED ISSUE #958: Workspace Option for tkn clustertask start
# Expected Behavior

Similar to what was implemented in #826 and #854 for `tkn pipeline start` and `tkn task start`, there should be a `workspace` option for `tkn clustertask start` implemented exactly as #826 and #854 were implemented to connect a workspace when using `tkn clustertask start`. 

This also should account for whether `tkn clustertask start` with workspaces should support an interactive option. Currently only `tkn pipeline start` supports an interactive option for providing a workspace, but both `tkn task start` and `tkn clustertask start` should also have this feature as well if `tkn pipeline start` supports this.

### LINKED ISSUE #1013: Enable interactive start for the clustertask
# Version and Operating System

**tkn Version:**
Latest

**Operating System:** 
All

# Expected Behavior
the `tkn task start` command is interactive now (it asks for parameter and resource values if not provided while starting the task), but the cluster task is not interactive (if we don't provide the expected parameter or the resource the taskrun fails with error `TaskRunValidationFailed`). The `tkn ct start` should be interactive to maintain consistency 

# Actual Behavior
`tkn ct start` is not interactive

# Steps to Reproduce the Problem

1. Create a clustertask with parameter
2. Start the clustertask without providing the parameter

# Additional Info
Below are the command logs
```
$ tkn t start task1 
? Value for param `test-param` of type `string`? abcdef
Taskrun started: task1-run-m2q4n

In order to track the taskrun progress run:
tkn taskrun logs task1-run-m2q4n -f -n veeresh-testing
[varadhya@localhost cli]$ 
[varadhya@localhost cli]$ tkn ct start buildah
Taskrun started: buildah-run-h8v8h

In order to track the taskrun progress run:
tkn taskrun logs buildah-run-h8v8h -f -n veeresh-testing
[varadhya@localhost cli]$ 
[varadhya@localhost cli]$ tkn tr ls
NAME                STARTED          DURATION   STATUS
buildah-run-h8v8h   5 seconds ago    ---        Failed(TaskRunValidationFailed)
task1-run-m2q4n     12 seconds ago   ---        Running(Pending)
[varadhya@localhost cli]$ 
```

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

This adds interactive mode to start a clustertask similar to task and pipeline start command to maintain consistency and also added `--workspace` flag as Workspaces needs to be used at the time of interactive start.

Closes #1013 
Closes #958 

Signed-off-by: vinamra28 <vinjain@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Add interactive start to ClusterTask start and also added `--workspace` flag for the interactive start
```

### CODE REVIEW

File: pkg/cmd/clustertask/start.go [hunk 1]
```diff
@@ -140,6 +157,7 @@ like cat,foo,bar
 	flags.AddShellCompletion(c.Flags().Lookup("serviceaccount"), "__kubectl_get_serviceaccount")
 	c.Flags().BoolVarP(&opt.Last, "last", "L", false, "re-run the ClusterTask using last TaskRun values")
 	c.Flags().StringSliceVarP(&opt.Labels, "labels", "l", []string{}, "pass labels as label=value.")
+	c.Flags().StringArrayVarP(&opt.Workspaces, "workspace", "w", []string{}, "pass the workspace.")
```
Comment (danielhelfand) [inline pkg/cmd/clustertask/start.go:160]: Can you please make the description something more informative to the user? I realize the other workspace options say the same thing, but it could help us address #895 as far as crafting a better one.

```suggestion
	c.Flags().StringArrayVarP(&opt.Workspaces, "workspace", "w", []string{}, "pass the workspace.")
```

File: pkg/options/start.go [hunk 2]
```diff
@@ -348,6 +348,229 @@ func (intOpts *InteractiveOpts) TaskWorkspaces(task *v1beta1.Task) error {
...
+
+func (intOpts *InteractiveOpts) ClusterTaskWorkspaces(clustertask *v1beta1.ClusterTask) error {
+	for _, ws := range clustertask.Spec.Workspaces {
+		fmt.Fprintf(intOpts.Stream.Out, "Please give specifications for the workspace: %s \n", ws.Name)
+		name, err := askParam("Name for the workspace :", intOpts.AskOpts)
+		if err != nil {
+			return err
+		}
+		workspace := "name=" + name
+		subPath, err := askParam("Value of the Sub Path :", intOpts.AskOpts, " ")
```
Comment (danielhelfand) [inline pkg/options/start.go:510]:
```suggestion
		subPath, err := askParam("Value of the Sub Path:", intOpts.AskOpts, " ")
```

File: test/e2e/build_templates.go [hunk 3]
```diff
@@ -53,6 +62,17 @@ func GetTaskList(c *Clients) *v1alpha1.TaskList {
 	return tasklist
 }
 
+func GetClusterTaskList(c *Clients) *v1alpha1.ClusterTaskList {
+
```
Comment (danielhelfand) [inline test/e2e/build_templates.go:66]: Nit: please remove this extra space

File: test/e2e/clustertask/start_test.go [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+					return err
+				}
+
+				c.Close()
+				return nil
+			}})
+	})
+
+	t.Logf("Deleting clustertask ")
+	e2e.Assert(t, kubectl.Delete(e2e.ResourcePath("read-file-clustertask.yaml")), icmd.Success)
```
Comment (danielhelfand) [inline test/e2e/clustertask/start_test.go:117]: Deleting the clustertask is unnecessary. It will be cleaned up after the tests complete.

File: test/e2e/cli.go [hunk 5]
```diff
@@ -151,6 +151,17 @@ func (k Kubectl) Create(args ...string) *icmd.Result {
 	return res
 }
 
+//Delete will help you to delete a resource in any namespace
```
Comment (danielhelfand) [inline test/e2e/cli.go:154]: This isn't needed. See this comment in `start_test.go`.

**Comment by vinamra28** [comment]
> Thanks for adding all the e2e testing for ClusterTasks. Could you please also add a test for starting a ClusterTask with `--workspace`?

@danielhelfand could you please review. I have done the required changes :sweat_smile:

**Comment by piyush-garg** [comment]
@danielhelfand I think this also resolves #958

**Comment by danielhelfand** [comment]
> @danielhelfand I think this also resolves #958

@piyush-garg Yes, it will! Will review this today @vinamra28.

File: pkg/cmd/clustertask/start.go [hunk 6]
```diff
@@ -140,6 +157,7 @@ like cat,foo,bar
 	flags.AddShellCompletion(c.Flags().Lookup("serviceaccount"), "__kubectl_get_serviceaccount")
 	c.Flags().BoolVarP(&opt.Last, "last", "L", false, "re-run the ClusterTask using last TaskRun values")
 	c.Flags().StringSliceVarP(&opt.Labels, "labels", "l", []string{}, "pass labels as label=value.")
+	c.Flags().StringArrayVarP(&opt.Workspaces, "workspace", "w", []string{}, "pass one or more workspaces to map to the corresponding physical volumes as name=name,claimName=pvcName or name=name,emptyDir=")
```
Comment (danielhelfand) [inline pkg/cmd/clustertask/start.go:160]: We should probably do some kind of follow up to not require `=` with `emptyDir`. Not the best UX in my opinion, but I realize that was a miss when this feature was originally added and doesn't have to slow down this pr.

File: pkg/cmd/clustertask/start_test.go [hunk 7]
```diff
@@ -313,6 +313,7 @@ func Test_ClusterTask_Start(t *testing.T) {
 				"-p", "print=boom,boom",
 				"-l", "key=value",
 				"-o", "code-image=output-image",
+				"-w", "name=test,claimName=pvc3",
```
Comment (danielhelfand) [inline pkg/cmd/clustertask/start_test.go:316]: Why do we need to add `-w` to every test? Wouldn't it be better to just create a test specifically for workspaces?

File: pkg/options/start.go [hunk 8]
```diff
@@ -348,10 +348,233 @@ func (intOpts *InteractiveOpts) TaskWorkspaces(task *v1beta1.Task) error {
...
+
+	resources, err := intOpts.pipelineResourcesByFormat(cs.Resource)
+	if err != nil {
+		return err
+	}
+	for _, res := range clustertask.Spec.Resources.Inputs {
+		options := resourceByType(resources, string(res.Type))
+		// directly create resource
+		if len(options) == 0 {
+			fmt.Fprintf(intOpts.Stream.Out, "no pipeline resource of type \"%s\" found in namespace: %s\n", string(res.Type), intOpts.Ns)
```
Comment (danielhelfand) [inline pkg/options/start.go:365]:
```suggestion
			fmt.Fprintf(intOpts.Stream.Out, "no Pipeline resource of type \"%s\" found in namespace: %s\n", string(res.Type), intOpts.Ns)
```

File: pkg/options/start.go [hunk 9]
```diff
@@ -348,10 +348,233 @@ func (intOpts *InteractiveOpts) TaskWorkspaces(task *v1beta1.Task) error {
...
+			fmt.Fprintf(intOpts.Stream.Out, "Please create a new \"%s\" resource for pipeline resource \"%s\"\n", string(res.Type), res.Name)
```
Comment (danielhelfand) [inline pkg/options/start.go:366]:
```suggestion
			fmt.Fprintf(intOpts.Stream.Out, "Please create a new \"%s\" resource for PipelineResource \"%s\"\n", string(res.Type), res.Name)
```

File: pkg/options/start.go [hunk 10]
```diff
@@ -348,10 +348,233 @@ func (intOpts *InteractiveOpts) TaskWorkspaces(task *v1beta1.Task) error {
...
+	resources, err := intOpts.pipelineResourcesByFormat(cs.Resource)
+	if err != nil {
+		return err
+	}
+
+	for _, res := range clustertask.Spec.Resources.Outputs {
+		options := resourceByType(resources, string(res.Type))
+		// directly create resource
+		if len(options) == 0 {
+			fmt.Fprintf(intOpts.Stream.Out, "no pipeline resource of type \"%s\" found in namespace: %s\n", string(res.Type), intOpts.Ns)
```
Comment (danielhelfand) [inline pkg/options/start.go:425]:
```suggestion
			fmt.Fprintf(intOpts.Stream.Out, "no Pipeline resource of type \"%s\" found in namespace: %s\n", string(res.Type), intOpts.Ns)
```

File: pkg/options/start.go [hunk 11]
```diff
@@ -348,10 +348,233 @@ func (intOpts *InteractiveOpts) TaskWorkspaces(task *v1beta1.Task) error {
...
+			fmt.Fprintf(intOpts.Stream.Out, "Please create a new \"%s\" resource for pipeline resource \"%s\"\n", string(res.Type), res.Name)
```
Comment (danielhelfand) [inline pkg/options/start.go:426]:
```suggestion
			fmt.Fprintf(intOpts.Stream.Out, "Please create a new \"%s\" resource for PipelineResource \"%s\"\n", string(res.Type), res.Name)
```

File: pkg/cmd/clustertask/start_test.go (hunk 7 above)
Comment (vinamra28) [reply pkg/cmd/clustertask/start_test.go:316]: The TaskSpec of the ClusterTask-1 consists of a workspace and that's why used the `-w` flag so that we don't get the prompt to input the workspace.

Comment (danielhelfand) [reply pkg/cmd/clustertask/start_test.go:316]: Can you create new test data instead of adding it? This will help to keep original tests as they were.

Comment (vinamra28) [reply pkg/cmd/clustertask/start_test.go:316]: @danielhelfand anyhow we need to modify the existing tasks because in the existing test data workspace is already defined so for their respective taskruns we need to add `-w` flag but sure I will add one more test data for the workspaces

**Comment by vinamra28** [comment]
@danielhelfand I have added some tests for the workspaces as well

**Comment by vinamra28** [comment]
@danielhelfand @piyush-garg I have rebased the PR and also worked upon the comments.

File: docs/cmd/tkn_clustertask_start.md [hunk 12]
```diff
@@ -40,6 +40,7 @@ like cat,foo,bar
   -s, --serviceaccount string    pass the serviceaccount name
       --showlog                  show logs right after starting the ClusterTask
       --timeout string           timeout for TaskRun
+  -w, --workspace stringArray    pass one or more workspaces to map to the corresponding physical volumes as name=name,claimName=pvcName or name=name,emptyDir=
```
Comment (danielhelfand) [inline docs/cmd/tkn_clustertask_start.md:43]: We'll also want to document `volumeClaimTemplateFile`, but I can do a follow up pr for that.

File: test/e2e/clustertask/start_test.go [hunk 13]
```diff
@@ -0,0 +1,114 @@
...
+	is "gotest.tools/v3/assert/cmp"
+	"gotest.tools/v3/icmd"
+	knativetest "knative.dev/pkg/test"
+)
+
+const (
+	tePipelineGitResourceName = "skaffold-git"
+)
+
+func TestClusterTaskInteractiveStartE2E(t *testing.T) {
```
Comment (danielhelfand) [inline test/e2e/clustertask/start_test.go:38]: There should also be a test here for `volumeClaimTemplateFile` with `-w`, but I can add that in a follow up pr.
