### PR TITLE
Fix slowness in executing tkn commands

### LINKED ISSUE #1153: Slow `tkn` operation
# Versions and Operating System

- Kubernetes version:

OpenShift 4.6

- Tekton Pipeline version:

nightly

- Operating System:

OSX

# Actual Behavior

`tkn pipeline ls` has been feeling very slow, the released or nightly version : 

i.e over 11s for a simple `tkn p ls` : 

```
% time ./bin/tkn p ls
NAME               AGE              LAST RUN   STARTED   DURATION   STATUS
pipeline-buildah   56 seconds ago   ---        ---       ---        ---
./bin/tkn p ls  0.14s user 0.07s system 1% cpu 11.329 total
```

or even longer for a `tkn p describe` : 

```
./bin/tkn p describe pipeline-buildah  0.18s user 0.09s system 1% cpu 26.565 total
```

It doesn't seem to be a latency since kubectl operation takes even less than a second : 

```
% time (k get pipeline >/dev/null && k describe pipeline pipeline-buildah >/dev/null)
( kubectl get pipeline > /dev/null && kubectl describe pipeline  > /dev/null;   0.17s user 0.05s system 22% cpu 0.984 total
```

### PR DESCRIPTION
**Pull request by piyush-garg**
This will fix the issue of slowness in
tkn commands. We were fetching apiGroupRes
details everytime in a api call using client-go.
Now we store the results and reuse in further
operations. So in a single tkn command execution
we fetch the details of apiGroupRes only once
and reuse in further operations api-call.

Example like for tkn pipelines ls command,
we need the pipelines and also pipelineruns
for all pipelines. We were fetching apiGroupRes
everytime like during fetching pipelines and further
pipelineruns which depends on no. of pipelines.
Now we store the result in single execution
and reuse this for all operations.

Refactoring in unit tests accordingly.

Remove redundant golden files.

Fix #1153

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
   Fix tkn slowness issue, taking lot of time
```

### CODE REVIEW

File: pkg/actions/gvr.go [hunk 1]
```diff
@@ -34,3 +37,12 @@ func GetGroupVersionResource(gr schema.GroupVersionResource, discovery discovery
 
 	return &gvr, nil
 }
+
+func InitializeAPIGroupRes(discovery discovery.DiscoveryInterface) error {
+	var err error
+	apiGroupRes, err = restmapper.GetAPIGroupResources(discovery)
```
Comment (danielhelfand) [inline pkg/actions/gvr.go:43]:
```suggestion
	apiGroupRes, err := restmapper.GetAPIGroupResources(discovery)
```

File: pkg/actions/gvr.go [hunk 2]
```diff
@@ -34,3 +37,12 @@ func GetGroupVersionResource(gr schema.GroupVersionResource, discovery discovery
 
 	return &gvr, nil
 }
+
+func InitializeAPIGroupRes(discovery discovery.DiscoveryInterface) error {
```
Comment (sthaha) [inline pkg/actions/gvr.go:41]: do we need a separate function for this?

File: pkg/clustertask/clustertask_test.go [hunk 3]
```diff
@@ -91,22 +92,28 @@ func TestClusterTask_List(t *testing.T) {
...
 			name:   "Multi clusterTasks",
 			client: c2,
+			params: p2,
 			want:   []string{"clustertask", "clustertask2"},
 		},
 	}
 
 	for _, tp := range testParams {
 		t.Run(tp.name, func(t *testing.T) {
+			if err := actions.InitializeAPIGroupRes(tp.params.Tekton.Discovery()); err != nil {
```
Comment (sthaha) [inline pkg/clustertask/clustertask_test.go:114]: Wouldn't this be initialised using `tp.params.Tekton.Discovery()` automatically?

File: pkg/actions/gvr.go (hunk 2 above)
Comment (piyush-garg) [reply pkg/actions/gvr.go:41]: we need this for unit tests to have the apiGroupRes, we need to call it from every test

File: pkg/clustertask/clustertask_test.go (hunk 3 above)
Comment (piyush-garg) [reply pkg/clustertask/clustertask_test.go:114]: No, it was not getting initialized

**Review by danielhelfand — COMMENTED** [review]
A question/comment:

1. For my own understanding, under what circumstances is `apiGroupRes==nil`, and how does it reset to nil?

2. This approach may also be useful for getting the apiVersion for `--dry-run` with start commands: 

https://github.com/tektoncd/cli/blob/1f0312a6f6b25a1b8a3ce8a36d4b065b3c60026f/pkg/cmd/pipeline/start.go#L859

https://github.com/tektoncd/cli/blob/1f0312a6f6b25a1b8a3ce8a36d4b065b3c60026f/pkg/cmd/task/start.go#L469

https://github.com/tektoncd/cli/blob/1f0312a6f6b25a1b8a3ce8a36d4b065b3c60026f/pkg/cmd/clustertask/start.go#L372

File: pkg/actions/gvr.go (hunk 1 above)
Comment (piyush-garg) [reply pkg/actions/gvr.go:43]: as `apiGroupRes` has been declared before, this is throwing errors

**Comment by piyush-garg** [comment]
> A question/comment:
> 
> 1. For my own understanding, under what circumstances is `apiGroupRes==nil`, and how does it reset to nil?
> 2. This approach may also be useful for getting the apiVersion for `--dry-run` with start commands:
> 
> https://github.com/tektoncd/cli/blob/1f0312a6f6b25a1b8a3ce8a36d4b065b3c60026f/pkg/cmd/pipeline/start.go#L859
> 
> https://github.com/tektoncd/cli/blob/1f0312a6f6b25a1b8a3ce8a36d4b065b3c60026f/pkg/cmd/task/start.go#L469
> 
> https://github.com/tektoncd/cli/blob/1f0312a6f6b25a1b8a3ce8a36d4b065b3c60026f/pkg/cmd/clustertask/start.go#L372

By default the apiGroupRes is nil, so after the first call it has the value. So everytime user execute a command, apiroupRes will be nil, and after any first API call it has the value, and we don't need to fetch this value again and again for all operations.

As you will execute another command after that, it will be nil again

File: pkg/actions/gvr.go [hunk 4]
```diff
@@ -20,10 +20,13 @@ import (
 	"k8s.io/client-go/restmapper"
 )
 
+var apiGroupRes []*restmapper.APIGroupResources
```
Comment (vdemeester) [inline pkg/actions/gvr.go:23]: We *may* want to use https://pkg.go.dev/sync?tab=doc#Once for this (to make it a little bit cleaner)

File: pkg/actions/gvr.go (hunk 2 above)
Comment (vdemeester) [reply pkg/actions/gvr.go:41]: Any reason we need to call it from every test ? I would *like* this fix to not have to modify all the tests.

File: pkg/clustertask/clustertask_test.go (hunk 3 above)
Comment (vdemeester) [reply pkg/clustertask/clustertask_test.go:114]: Same as @sthaha , `List` seems to call `actions.List` that calls `GetGroupVersionResource`, so I don't understand why we need to call `InitializeAPIGroupRes` before.

**Review by vdemeester — COMMENTED** [review]
The diff seems way too big for that fix. I would think we don't need to update tests, at least not calling `InitializeAPIGroupRes` before each. Also, this feels a very good usecase for `sync.Once` :upside_down_face:

File: pkg/actions/gvr.go (hunk 2 above)
Comment (piyush-garg) [reply pkg/actions/gvr.go:48]: Improved according to comments

File: pkg/clustertask/clustertask_test.go (hunk 3 above)
Comment (piyush-garg) [reply pkg/clustertask/clustertask_test.go]: Because it is getting initialized in running first test, then for second test it was not getting initialized as the value is already so there, so getting called from every test to have the value once.

File: pkg/actions/gvr.go (hunk 4 above)
Comment (piyush-garg) [reply pkg/actions/gvr.go]: Updated to use sync

**Comment by piyush-garg** [comment]
@sthaha @danielhelfand @vdemeester @chmouel Refactored the PR according to comments

File: pkg/cmd/clustertriggerbinding/clustertriggerbinidng_test.go [hunk 5]
```diff
@@ -0,0 +1,31 @@
+// Copyright © 2020 The Tekton Authors.
```
Comment (danielhelfand) [inline pkg/cmd/clustertriggerbinding/clustertriggerbinidng_test.go:1]: Just a question. Is this related to this pr?

**Review by danielhelfand — COMMENTED** [review]
/lgtm

File: pkg/cmd/clustertriggerbinding/clustertriggerbinidng_test.go (hunk 5 above)
Comment (piyush-garg) [reply pkg/cmd/clustertriggerbinding/clustertriggerbinidng_test.go:1]: I was going through tests, and I found this is missing one and there are few redundant golden files which are not used, so did all refactoring :D

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Review by vdemeester — APPROVED** [review]
/meow

File: pkg/test/builder/apiresource.go [hunk 6]
```diff
@@ -36,9 +36,9 @@ func APIResourceList(version string, kinds []string) []*metav1.APIResourceList {
 func apiresources(version string, kinds []string) []metav1.APIResource {
 	apires := make([]metav1.APIResource, 0)
 	for _, kind := range kinds {
-		namespaced := false
+		namespaced := true
 		if strings.Contains(kind, "cluster") {
-			namespaced = true
+			namespaced = false
```
Comment (chmouel) [inline pkg/test/builder/apiresource.go:41]: 😅  was it used anywhere?

Comment (piyush-garg) [reply pkg/test/builder/apiresource.go:41]: not sure, It did not make any difference anywhere

**Comment by chmouel** [comment]
Looks good to me, but let's wait for @sthaha +1 before the final approve.

**Comment by piyush-garg** [comment]
@chmouel It is merged now, but if @sthaha has any concerns, I will raise separate PR to address those. Please give it a review @sthaha

**Comment by sthaha** [comment]
@piyush-garg I had a look at the code and I don't see an easy way to reset the cache automatically for each test  without quite some refactor. 

@piyush-garg however I was wondering if we could resync the cache using the discovery.Interface() if there is a cache miss before it errors. I believe that may solve the need to add `InitializeCache` in all tests.
