### PR TITLE
Include TaskRun Failure Message in Logs

### LINKED ISSUE #467: Error Message for tkn task start Difficult to Find
When using `tkn task start`, logs instantly start as expected, but a failure results in the following message:

```
Error: task build-docker-image-from-git-source create failed or has not started yet or pod for task not yet available
```

This doesn't do the best job of communicating the issue if a failure has occurred. You need to dig deeper by looking at `tkn tr desc` to find what the error was:

```
Name:        build-docker-image-from-git-source-run-g6bfb
Namespace:   default
Task Ref:    build-docker-image-from-git-source

Status
STARTED          DURATION    STATUS
14 minutes ago   ---         Failed(TaskRunValidationFailed)

Message
invalid input resources: TaskRun's declared resources didn't match usage in Task: Didn't provide required values: [docker-source]

Input Resources
No resources

Output Resources
No resources

Params
No params

Steps
No steps
```

It would be better if this information was communicated via logs of the task run, but, at the very least, we could print some type of message of where to look for the error message (i.e. `tkn taskrun desc`).

# Expected Behavior

Find specific error message in task run logs

# Actual Behavior

Error in logs doesn't communicate issue for taskrun failure

# Steps to Reproduce the Problem
Run task with inputs/outputs
1. Create task with input
2. `tkn task start <task name> #Don't provide inputs/outputs

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #467 

This pull request adds a check if the taskrun has failed while starting up and includes the failure message in the taskrun logs.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [x] Run the code checkers with `make check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```
Make error message for taskrun start up failure easier to find
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
So my only concern with this is, it will work only for `follow` mode. Is that the target?

**Comment by danielhelfand** [comment]
> So my only concern with this is, it will work only for `follow` mode. Is that the target?

No, you're right. We should also do this for non follow mode. It would make sense to edit [here](https://github.com/tektoncd/cli/blob/d1c9dfbd4583c3f2d00c82c0e92c5cade04b93c4/pkg/cmd/taskrun/log_reader.go#L137) to display the error.

**Comment by piyush-garg** [comment]
Better to do something for both, and the differentiation starts [here](https://github.com/tektoncd/cli/blob/d1c9dfbd4583c3f2d00c82c0e92c5cade04b93c4/pkg/cmd/taskrun/log_reader.go#L73)

File: pkg/cmd/taskrun/log_reader.go [hunk 1]
```diff
@@ -273,11 +279,25 @@ func (lr *LogReader) waitUntilPodNameAvailable(timeout time.Duration) (*v1alpha1
 			}
 			if first {
 				first = false
-				fmt.Fprintln(lr.Stream.Out, "Task still running ...")
+				fmt.Fprintln(lr.Stream.Out, "Waiting for logs to be available...")
```
Comment (danielhelfand) [inline pkg/cmd/taskrun/log_reader.go]: Updating message here as it can be misleading. For instance, if you run `tkn taskrun logs -f` after a task has failed, it would print `Task still running` even though it has already failed.

File: pkg/cmd/taskrun/log_reader.go [hunk 2]
```diff
@@ -134,7 +140,7 @@ func (lr *LogReader) readAvailableLogs(tr *v1alpha1.TaskRun) (<-chan Log, <-chan
 	p := pods.New(podName, lr.Ns, kube, lr.Streamer)
 	pod, err := p.Get()
 	if err != nil {
-		return nil, nil, errors.Wrap(err, fmt.Sprintf("task %s failed", lr.Task))
+		return nil, nil, errors.Wrap(err, fmt.Sprintf("task %s has failed", lr.Task))
```
Comment (danielhelfand) [inline pkg/cmd/taskrun/log_reader.go]: Question here is whether to include `err.Error()` or `tr.Condition[0].message`?

File: pkg/cmd/taskrun/describe.go [hunk 3]
```diff
@@ -184,5 +184,6 @@ func hasFailed(tr *v1alpha1.TaskRun) string {
 	if tr.Status.Conditions[0].Status == corev1.ConditionFalse {
 		return tr.Status.Conditions[0].Message
 	}
+
```
Comment (vdemeester) [inline pkg/cmd/taskrun/describe.go]: :thinking:
