### PR TITLE
--dry-run Option for tkn pipeline start

### LINKED ISSUE #372: Flag to print PipelineRun when calling `tkn pipeline start`
# Expected Behavior

I'd like to be able to see the PipelineRun that `tkn` generates before I decide to actually start it.

# Actual Behavior

At the moment `tkn pipeline start` runs the pipeline but cannot show me what the PipelineRun will be before I start it.

# Steps to Reproduce the Problem

1. tkn pipeline start <name-of-pipeline> <flags-for-pipeline>

# Additional Info

I'm using `tkn` for a public release of Tekton Pipelines. Before I commit the PipelineRun that will do the release I'd like to review it (and maybe even copy/paste it somewhere else for other people to see).

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #372 

# Changes

This pull request adds a `--dry-run` option for `tkn pipeline start`. The idea would be to print the pipelinerun to stdout so a user can look over the pipelinerun without actually running the pipeline. 

An `--output` option will also be made available to output the dry run in yaml or json:

**Output the pipeline named pipelinename in namespace ns in yaml:**

`tkn pipeline start pipelinename -n ns --dry-run --output yaml`

**Output the pipeline named pipelinename in namespace ns in json:**
`tkn pipeline start pipelinename -n ns --dry-run -o json`

**Not using output flag with --dry-run uses yaml output default:**

`tkn pipeline start pipelinename -n ns --dry-run`

Example out:

**output = json**

```json
{
	"kind": "PipelineRun",
	"apiVersion": "tekton.dev/v1alpha1",
	"metadata": {
		"generateName": "deploy-pipeline-run-",
		"namespace": "default",
		"creationTimestamp": null
	},
	"spec": {
		"pipelineRef": {
			"name": "deploy-pipeline"
		},
		"resources": [
			{
				"name": "app-git",
				"resourceRef": {
					"name": "nodejs-ex-git"
				}
			},
			{
				"name": "app-image",
				"resourceRef": {
					"name": "nodejs-ex-image"
				}
			}
		],
		"serviceAccountName": "default",
		"podTemplate": {}
	},
	"status": {}
}
```

**output = yaml**

```yaml
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: deploy-pipeline-run-
  namespace: default
spec:
  pipelineRef:
    name: deploy-pipeline
  podTemplate: {}
  resources:
  - name: app-git
    resourceRef:
      name: nodejs-ex-git
  - name: app-image
    resourceRef:
      name: nodejs-ex-image
  serviceAccountName: default
status: {}

```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [x] Run the code checkers with `make check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```
Add --dry-run option to tkn pipeline start to preview a pipelinerun
```

### CODE REVIEW

File: pkg/cmd/pipeline/start.go [hunk 1]
```diff
@@ -376,6 +381,10 @@ func getOptionsByType(resources resourceOptionsFilter, restype string) []string
 
 func (opt *startOptions) startPipeline(pName string) error {
 	pr := &v1alpha1.PipelineRun{
+		TypeMeta: metav1.TypeMeta{
+			APIVersion: "tekton.dev/v1alpha1",
```
Comment (danielhelfand) [inline pkg/cmd/pipeline/start.go]: How to specify the APIVersion seems difficult. This could maybe be pulled from the pipeline?

File: pkg/cmd/pipeline/start.go [hunk 2]
```diff
@@ -385,6 +394,19 @@ func (opt *startOptions) startPipeline(pName string) error {
 		},
 	}
 
+	if opt.DryRun != "" {
+		prBytes, err := yaml.Marshal(pr)
+		if err != nil {
+			return err
+		}
+
+		if err := ioutil.WriteFile(opt.DryRun, prBytes, os.ModePerm); err != nil {
```
Comment (danielhelfand) [inline pkg/cmd/pipeline/start.go]: I do not have unit tests for this since it writes a local file. Would it make sense to write the file and then delete it as part of the unit test?

**Comment by chmouel** [comment]
I like the idea! thinking about it, what do you think about `-o yaml -f file.yaml` for this? as -o json may be useful too...

File: pkg/cmd/pipeline/start.go (hunk 2 above)
Comment (chmouel) [reply pkg/cmd/pipeline/start.go]: not sure if that's the proper way but that's how i would do it 😅

Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go]: Sure, I'll try it.

**Comment by danielhelfand** [comment]
> I like the idea! thinking about it, what do you think about `-o yaml -f file.yaml` for this? as -o json may be useful too...

🤔 Yeah, I could see this. So potentially convert `--dry-run` to a boolean and specify the outputs with `-o` and `-f`. Maybe default to yaml if nothing is specified?

File: pkg/cmd/pipeline/start.go (hunk 2 above)
Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go]: Wondering if this approach is the right way here, but there are at least unit tests for errors/marshaling the pipelinerun.

**Comment by vdemeester** [comment]
To add more to my previous comment, I wanna be able to do something like `tkn pipeline start --dry-run --output=json | sed … | kubectl apply -f -` or simial things. The PR, as-is, force me to use a `-f` and write a file, which might not be needed.

**Comment by chmouel** [comment]
humm yeah make sense, sorry @danielhelfand that i made. you change it  🙇

**Comment by danielhelfand** [comment]
> To add more to my previous comment, I wanna be able to do something like `tkn pipeline start --dry-run --output=json | sed … | kubectl apply -f -` or simial things. The PR, as-is, force me to use a `-f` and write a file, which might not be needed.

Yeah, that makes sense. I can see scenarios where you don't actually want to output a file so makes sense. Also makes it easier to write tests for.

Would `tkn pipeline start --dry-run --output=json` then print the pipelinerun in json format in the case when not using >?

**Comment by vdemeester** [comment]
> Would `tkn pipeline start --dry-run --output=json` then print the pipelinerun in json format in the case when not using >?

Yes :angel:

File: pkg/cmd/pipeline/start_test.go [hunk 3]
```diff
@@ -360,6 +360,109 @@ func TestPipelineStart_ExecuteCommand(t *testing.T) {
...
+				"-r=source=scaffold-git",
+				"-p=pipeline-param=value1",
+				"-l=jemange=desfrites",
+				"-n", "ns",
+				"--dry-run",
+			},
+			namespace: "",
+			input:     cs2,
+			wantError: false,
+			want: `apiVersion: tekton.dev/v1alpha1
```
Comment (danielhelfand) [inline pkg/cmd/pipeline/start_test.go]: I think these should be golden files, but I think it would be better to refactor these to golden files in a separate pr.

File: pkg/cmd/pipeline/start.go (hunk 1 above)
Comment (chmouel) [reply pkg/cmd/pipeline/start.go]: I think we would want at least to have it in a global since that string is scattered everywhere, but that's a refactoring that can be done for later....

File: pkg/cmd/pipeline/start.go [hunk 4]
```diff
@@ -567,3 +581,29 @@ func (opt *startOptions) createPipelineResource(resName string, resType v1alpha1
...
+	if format == "" || format == "yaml" {
+		prBytes, err := yaml.Marshal(pr)
+		if err != nil {
+			return err
+		}
+		fmt.Fprintf(s.Out, "%s\n", prBytes)
+	}
+
+	if format == "json" {
+		prBytes, err := json.MarshalIndent(pr, "", "\t")
```
Comment (danielhelfand) [inline pkg/cmd/pipeline/start.go]: Can do something besides tab for indent if there are thoughts on that.

File: pkg/cmd/pipeline/start.go (hunk 1 above)
Comment (vdemeester) [reply pkg/cmd/pipeline/start.go]: :thinking: I think it's fine for now, but indeed, good question. I would guess we default to a hard coded version, and we could have some smart code that checks what api version are available in the cluster (and adjust from it or error out from there)

File: pkg/cmd/pipeline/start.go (hunk 4 above)
Comment (vdemeester) [reply pkg/cmd/pipeline/start.go]: no idea :sweat_smile: 
I think `kubectl` prints it without `indent` and let the user pass it through a tool for indent ?

/cc @chmouel

File: pkg/cmd/pipeline/start_test.go (hunk 3 above)
Comment (vdemeester) [reply pkg/cmd/pipeline/start_test.go]: Yes they should be golden files :angel: Could be done now or in a follow-up, as you want :wink:

File: pkg/cmd/pipeline/start.go (hunk 4 above)
Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go]: I guess I would like the indent here if the behavior is to print for the end user to see.

Comment (chmouel) [reply pkg/cmd/pipeline/start.go]: they are spaces on kubectl output or at least according to whitespace-mode in emacs

as long it's yamllint compatible i think it's fine  for me!

> I guess I would like the indent here if the behavior is to print for the end user to see.

It's fine either way? printed to end user or not we could do indent?

Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go]: Without the indent, it's all crammed to the left like below:

```json
{
"kind": "PipelineRun",
"apiVersion": "tekton.dev/v1alpha1",
"metadata": {
"generateName": "deploy-pipeline-run-",
"namespace": "default",
"creationTimestamp": null
},
"spec": {
"pipelineRef": {
"name": "deploy-pipeline"
},
"resources": [
{
"name": "app-git",
"resourceRef": {
"name": "nodejs-ex-git"
}
},
{
"name": "app-image",
"resourceRef": {
"name": "nodejs-ex-image"
}
}
],
"serviceAccountName": "default",
"podTemplate": {}
},
"status": {}
}
```

With the indent, it's as follows:

```json
{
	"kind": "PipelineRun",
	"apiVersion": "tekton.dev/v1alpha1",
	"metadata": {
		"generateName": "deploy-pipeline-run-",
		"namespace": "default",
		"creationTimestamp": null
	},
	"spec": {
		"pipelineRef": {
			"name": "deploy-pipeline"
		},
		"resources": [
			{
				"name": "app-git",
				"resourceRef": {
					"name": "nodejs-ex-git"
				}
			},
			{
				"name": "app-image",
				"resourceRef": {
					"name": "nodejs-ex-image"
				}
			}
		],
		"serviceAccountName": "default",
		"podTemplate": {}
	},
	"status": {}
}
```

I think I'll keep as is.

File: pkg/cmd/pipeline/start_test.go (hunk 3 above)
Comment (danielhelfand) [reply pkg/cmd/pipeline/start_test.go]: Will refactor them all in a separate pr.

File: pkg/cmd/pipeline/start.go (hunk 4 above)
Comment (chmouel) [reply pkg/cmd/pipeline/start.go]: yes please big +1 on indents! any chanced to check if yamllint can validate it ? (i mean not a test but manually)

Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go]: Yes, it works with yamllint.

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽
