### PR TITLE
Sort Steps for tkn taskrun desc by StartedAt

### LINKED ISSUE #460: Sort Steps by Order of Execution for tkn tr desc
Following up on #450.

The steps shown by `tkn taskrun describe` don't appear in the order that they are to be executed. Specifically, steps not explicitly defined as part of the task definition that show up as part of a task run make it confusing as to the order of what is to be executed. 

An example of a step not explicitly defined as part of a task but appears as part of a task run is [`s2i-nodejs`](https://github.com/openshift/pipelines-catalog/blob/0157bb7c7161c55fecaa6835137d01c61a360ec8/s2i-nodejs/s2i-nodejs-task.yaml) where an `image-digest-exporter` step appears that is not part of the task definition.

# Expected Behavior

Steps appear in order they are to be executed with `tkn tr desc`.

# Actual Behavior

Steps explicitly defined appear in correct order, but steps not part of task definition appear out of order.

# Steps to Reproduce the Problem

1. Use the `s2i-nodejs` task to create a task run
2. Use what's currently in master for tkn and run `./tkn tr desc <tr_name>`
3. View the `Steps` portion of the output from `tkn tr desc`

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #460 

This pull request sorts steps that are part of a TaskRun by start time. The start time is from a list of StepStates part of the TaskRun. Each StepState has a Terminated/Running container state from which the `StartedAt` field can be pulled. If the container state is in a waiting state (i.e. PodInitializing), the order will be determined by how steps are ordered for the Task.

# Submitter Checklist

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [x] Run the code checkers with `make check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```
Sort steps by start time for tkn tr desc
```

### CODE REVIEW

File: pkg/cmd/taskrun/describe.go [hunk 1]
```diff
@@ -194,3 +198,18 @@ func hasFailed(tr *v1alpha1.TaskRun) string {
 
 	return ""
 }
+
+func sortStepStatesByStartTime(steps []v1alpha1.StepState) []v1alpha1.StepState {
+	sort.Slice(steps, func(i, j int) bool {
+		if steps[j].Terminated == nil {
```
Comment (danielhelfand) [inline pkg/cmd/taskrun/describe.go]: /hold

I'm going to look into using `Running`'s `StartedAt` so `Running` steps can also be sorted

Comment (danielhelfand) [reply pkg/cmd/taskrun/describe.go]: Resolved

/hold cancel

**Comment by danielhelfand** [comment]
/hold

I would like to do some research on what exactly leads to the ordering taking place and why the task ordering of the steps is not enough to ensure proper ordering.

File: go.sum [hunk 2]
```diff
@@ -426,6 +426,7 @@ knative.dev/caching v0.0.0-20190719140829-2032732871ff/go.mod h1:dHXFU6CGlLlbzaW
 knative.dev/pkg v0.0.0-20190909195211-528ad1c1dd62 h1:0neKnC9hstF5Lewj6OaAJdXqk22IZ7pnOPQ8Zl8cfq4=
 knative.dev/pkg v0.0.0-20190909195211-528ad1c1dd62/go.mod h1:pgODObA1dTyhNoFxPZTTjNWfx6F0aKsKzn+vaT9XO/Q=
 knative.dev/pkg v0.0.0-20200108203553-8c6241207427 h1:swUPz/GhGE0bdXX8Ys6AXhjshbCcYXgW9weH7LvK28U=
+knative.dev/pkg v0.0.0-20200109235555-79d67498c2c4 h1:J8TW2j/+ESdQkL3aH2vF+FYbfLrEes58a0MeMxW7E+E=
```
Comment (chmouel) [inline go.sum]: Is that what you wanted to have?

File: pkg/cmd/taskrun/describe.go [hunk 3]
```diff
@@ -194,3 +198,45 @@ func hasFailed(tr *v1alpha1.TaskRun) string {
 
 	return ""
 }
+
+func sortStepStatesByStartTime(steps []v1alpha1.StepState) []v1alpha1.StepState {
```
Comment (chmouel) [inline pkg/cmd/taskrun/describe.go]: I think this function is a good candidate for a small and contained unit test 👼

**Comment by chmouel** [comment]
> I would like to do some research on what exactly leads to the ordering taking place and why the task ordering of the steps is not enough to ensure proper ordering.

I think the ordering is hard on tekton because all steps are started waiting with entrypoint for others, and we don't know which one wait for which

**Comment by danielhelfand** [comment]
/hold cancel

Think this is ready for another review. I have done done some research with the original task that raised this issue: [`s2i-nodejs`](https://github.com/openshift/pipelines-catalog/tree/master/s2i-nodejs). Sorting the steps by start time does put them in the correct order. You can use the task and reproduce the issue in #460. The changes here resolve it.
