### PR TITLE
Fix TaskRun order in `tkn pr logs`

### LINKED ISSUE #1372: `tkn pr logs <pr-name>` does not show logs of the task in the order that they are executed
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  $ kubectl version
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"5797eaecac19b9c0e4d10d3d6b559c074e3c3c88", GitTreeState:"clean", BuildDate:"2021-01-27T07:28:48Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+7d0a2b2", GitCommit:"7d0a2b269a27413f5f125d30c9d726684886c69a", GitTreeState:"clean", BuildDate:"2021-04-16T13:08:35Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  $ tkn version
  Client version: 0.18.0
  Pipeline version: v0.22.0
  Triggers version: v0.12.1

  ```

- Operating System:

  ```
  All
  ```

# Expected Behavior
`tkn pr logs <pr-name>` should show logs of the task in the order that they are executed

# Actual Behavior
`tkn pr logs <pr-name>` shows the logs of the task in the order that they have been written whilte creating the pipeline.
Ex: for the below Pipeline, when the pipeline is still running the logs are shown in proper order but when the pipelinerun is completed the `tkn pr logs <pr-name> shows the log of `second-task` first and shows the log of `first-task`
```
tasks:
    - name: secondt-ask
      params:
        - name: print-message
          value: second-task
      runAfter:
        - first-task
      taskRef:
        kind: Task
        name: echo-task
    - name: first-task
      params:
        - name: print-message
          value: first-task
      taskRef:
        kind: Task
        name: echo-task
```

# Additional Info
**Command Execution logs:**
```
$ tkn p start echo-pipeline --showlog
PipelineRun started: echo-pipeline-run-2xt2t
Waiting for logs to be available...
[first-task : unnamed-0] first-task
[first-task : unnamed-0] + echo first-task

[secondt-ask : unnamed-0] + echo second-task
[secondt-ask : unnamed-0] second-task

$ 
$ tkn pr logs echo-pipeline-run-2xt2t
[secondt-ask : unnamed-0] + echo second-task
[secondt-ask : unnamed-0] second-task

[first-task : unnamed-0] first-task
[first-task : unnamed-0] + echo first-task
```

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Fixes #1372

Add a sort to TaskRun list in a finished PipelineRun, to print
logs from TaskRun as per the execution order.

example pipeline: 
- [pipeline definition](https://gist.github.com/nikhil-thomas/290cd46353060d438f706cdd4026e0ac)

Screenshot 2021-06-04 at 3 51 52 PM

- [Live log](https://gist.github.com/nikhil-thomas/be56f5c658b054781abb1e3a81aac541)

- Log after completion:
   - [log - existing behavior](https://gist.github.com/nikhil-thomas/d735ea47ba3198e0f047ec360f83be6a)
   - [log - new behavior](https://gist.github.com/nikhil-thomas/56cdad75e987300380af42fe8fbac596)

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
- TaskRun Logs are listed in the appropriate order in `tkn pipelinerun logs` command. Fixes: #1372 ```

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
example pipeline: 
Screenshot 2021-06-04 at 3 51 52 PM

Live log: https://gist.github.com/nikhil-thomas/be56f5c658b054781abb1e3a81aac541

Log after completion:
- existing behavior: https://gist.github.com/nikhil-thomas/d735ea47ba3198e0f047ec360f83be6a
- new behavior: https://gist.github.com/nikhil-thomas/56cdad75e987300380af42fe8fbac596

**Comment by nikhil-thomas** [comment]
@piyush-garg @pradeepitm12 
i think i need to update the unit-tests.
could you help me with it.

File: pkg/taskrun/taskrun.go [hunk 1]
```diff
@@ -15,17 +15,39 @@
...
 
 type Run struct {
-	Name    string
-	Task    string
-	Retries int
+	Name           string
+	Task           string
+	Retries        int
+	StartTime      *metav1.Time
+	CompletionTime *metav1.Time
```
Comment (pradeepitm12) [inline pkg/taskrun/taskrun.go:33]: May be we need to add CompletionTime https://github.com/tektoncd/cli/blob/c2f113546808911c915cdfd34789233f34a61ae6/pkg/cmd/pipelinerun/logs_test.go#L469

tb.TaskRunCompletionTime(time),

**Comment by pradeepitm12** [comment]
@nikhil-thomas 
We can remove the [test which is using v1alpha1 test builders](https://github.com/tektoncd/cli/blob/c2f113546808911c915cdfd34789233f34a61ae6/pkg/cmd/pipelinerun/logs_test.go#L439)
Also, we already have the same [test with v1beta1 structs ](https://github.com/tektoncd/cli/blob/c2f113546808911c915cdfd34789233f34a61ae6/pkg/cmd/pipelinerun/logs_test.go#L1328)

File: pkg/taskrun/taskrun.go [hunk 2]
```diff
@@ -68,17 +90,20 @@ func SortTasksBySpecOrder(pipelineTasks []v1beta1.PipelineTask, pipelinesTaskRun
 	for name, t := range pipelinesTaskRuns {
 		trNames[t.PipelineTaskName] = name
 	}
+	trs := Runs{}
 
-	trs := []Run{}
 	for _, ts := range pipelineTasks {
 		if n, ok := trNames[ts.Name]; ok {
+			trStatusFields := pipelinesTaskRuns[n].Status.TaskRunStatusFields
```
Comment (pradeepitm12) [inline pkg/taskrun/taskrun.go:97]: There are two test failing 
[TestPipelinerunLog_completed_taskrun_only](https://github.com/tektoncd/cli/blob/c2f113546808911c915cdfd34789233f34a61ae6/pkg/cmd/pipelinerun/logs_test.go#L1328)
and 
[TestPipelinerunLog_completed_taskrun_only_v1beta1](https://github.com/tektoncd/cli/blob/c2f113546808911c915cdfd34789233f34a61ae6/pkg/cmd/pipelinerun/logs_test.go#L1328)
`pipelinesTaskRuns[n].Status.TaskRunStatusFields` field is required in pipelinerun test struct 
I tried adding it for [v1beta1 test ](https://gist.github.com/pradeepitm12/999f9f853e1cc9c1f65d6c7befd69b05) and it works. 
we can try adding the fields to [TestPipelinerunLog_completed_taskrun_only](https://github.com/tektoncd/cli/blob/c2f113546808911c915cdfd34789233f34a61ae6/pkg/cmd/pipelinerun/logs_test.go#L1328) also but we can remove it as this is same as the other one only diff of version v1alpha1 v1beta1

Comment (nikhil-thomas) [reply pkg/taskrun/taskrun.go:97]: Thanks 👍 
resolved 🧑‍💻

**Review by pradeepitm12 — APPROVED** [review]
/lgtm
