### PR TITLE
Fix output=name for pipelinerun list

### LINKED ISSUE #660: `tkn name -o name` is broken
Using tkn name -o name is broken and output an error message :

```
Error: list types are not supported by name printing: *v1alpha1.PipelineRunList
```

/assign
/kind bug

### PR DESCRIPTION
**Pull request by chmouel**
Let's fix -o name for pipelinerun listing the same way we can do 👍 

```
k get pr -o name
```

Let's do it for `tkn`

Will add the other command in following PR.

Closes #660

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [ ] Run the code checkers with `make check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

File: pkg/cmd/pipelinerun/list.go [hunk 1]
```diff
@@ -89,7 +89,16 @@ List all PipelineRuns in a namespace 'foo':
 				return err
 			}
 
-			if output != "" && prs != nil {
+			if output != "" && output == "name" && prs != nil {
```
Comment (danielhelfand) [inline pkg/cmd/pipelinerun/list.go]:
```suggestion
			if output == "name" && prs != nil {
```

Comment (chmouel) [reply pkg/cmd/pipelinerun/list.go]: oh yeah too much copy pasta :D
