### PR TITLE
Fix interactive input params on pipeline start

### LINKED ISSUE #465: Interactive start pipeline throws error
# Expected Behavior

`tkn pipeline start` should work

# Actual Behavior

It throws error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x131a278]

goroutine 1 [running]:
github.com/tektoncd/cli/pkg/cmd/pipeline.(*startOptions).getInputParams(0xc000129040, 0xc000202000, 0x1, 0x1)
	/home/pgarg/go/src/github.com/tektoncd/cli/pkg/cmd/pipeline/start.go:255 +0x138
github.com/tektoncd/cli/pkg/cmd/pipeline.(*startOptions).getInput(0xc000129040, 0x7ffcea1c4105, 0xd, 0x1916e01, 0xc000735b00)
	/home/pgarg/go/src/github.com/tektoncd/cli/pkg/cmd/pipeline/start.go:191 +0x132
github.com/tektoncd/cli/pkg/cmd/pipeline.(*startOptions).run(0xc000129040, 0x7ffcea1c4105, 0xd, 0x1916e20, 0xc000010020)
	/home/pgarg/go/src/github.com/tektoncd/cli/pkg/cmd/pipeline/start.go:157 +0x43
github.com/tektoncd/cli/pkg/cmd/pipeline.startCommand.func3(0xc0002db8c0, 0xc0002cefd0, 0x1, 0x1, 0x0, 0x0)
	/home/pgarg/go/src/github.com/tektoncd/cli/pkg/cmd/pipeline/start.go:137 +0x123
github.com/spf13/cobra.(*Command).execute(0xc0002db8c0, 0xc0002cefa0, 0x1, 0x1, 0xc0002db8c0, 0xc0002cefa0)
	/home/pgarg/go/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:832 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f6b00, 0xc000143590, 0xc0000f6b00, 0xc000050118)
	/home/pgarg/go/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:920 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/pgarg/go/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:870
main.main()
	/home/pgarg/go/src/github.com/tektoncd/cli/cmd/tkn/main.go:31 +0x4b

```

# Steps to Reproduce the Problem

1. Create a pipeline which has param with no default
2. Start pipeline and provide param value using interactive
3. Get the error

# Additional Info

```
It fails when you have params with no default either string or array. 
Also if you have array param with a default value, it does not take that value.
```

/kind bug
/assign

### PR DESCRIPTION
**Pull request by piyush-garg**
This will fix pipeline start throwing
error on interactive input params if
the params is of type array or string
without default value

Also fix array param with default input
as the question was incorrectly asked

Fix #465

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [x] Run the code checkers with `make check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

File: pkg/cmd/pipeline/start.go [hunk 1]
```diff
@@ -247,14 +248,24 @@ func (opt *startOptions) getInputResources(resources resourceOptionsFilter, pipe
 
 func (opt *startOptions) getInputParams(pipeline *v1alpha1.Pipeline) error {
 	for _, param := range pipeline.Spec.Params {
-		var ans string
+		var ans, ques, defaultValue string
+		ques = fmt.Sprintf("Value of param `%s` of type `%s`?", param.Name, param.Type)
```
Comment (danielhelfand) [inline pkg/cmd/pipeline/start.go]:
```suggestion
		ques = fmt.Sprintf("Is value of param `%s` of type `%s`?", param.Name, param.Type)
```

**Comment by danielhelfand** [comment]
Other than minor prompt edit, looks good to me.

File: pkg/cmd/pipeline/start.go (hunk 1 above)
Comment (piyush-garg) [reply pkg/cmd/pipeline/start.go]: its a question, which asks the value of params, `Is the value` does not look good to me

Comment (danielhelfand) [reply pkg/cmd/pipeline/start.go]: Okay, I think it reads a little clearer, but it’s a nit. If it comes up again, we can change it later.

Comment (vdemeester) [reply pkg/cmd/pipeline/start.go]: shouldn't it be "value **for** param …" ?

Comment (piyush-garg) [reply pkg/cmd/pipeline/start.go]: that change I can make

Comment (piyush-garg) [reply pkg/cmd/pipeline/start.go]: Fixed.
