### PR TITLE
Choose the first pipeline if only one available

### LINKED ISSUE #262: Interactive selection should choose automatically the first choice if there is only one choice
# Expected Behavior

Not asking for interactive menu when there is only one choice

# Actual Behavior

image

# Steps to Reproduce the Problem

1. tkn pipeline logs cli-release-pipeline

### PR DESCRIPTION
**Pull request by chmouel**
Closes #262

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

File: pkg/cmd/pipeline/logs_test.go [hunk 1]
```diff
@@ -663,6 +663,62 @@ func TestLogs_interactive_ask_run_last_run(t *testing.T) {
...
+		},
+	})
+
+	tests := []promptTest{
+		{
+			name:    "basic interaction",
+			cmdArgs: []string{pipelineName},
+
+			procedure: func(c *expect.Console) error {
+				if _, err := c.ExpectString("output-pipeline"); err == nil {
```
Comment (hrishin) [inline pkg/cmd/pipeline/logs_test.go]: Not sure what it's asserting?
Is the name of pipelinerun name?

Comment (chmouel) [reply pkg/cmd/pipeline/logs_test.go]: that's a good question, i copied paste the test from later on (the one about --last), i guess it's making sure there is no output

Comment (hrishin) [reply pkg/cmd/pipeline/logs_test.go]: cool :+1:
