### PR TITLE
Fix clustertask start command with --last flag

### LINKED ISSUE #1331: tkn clustertask start <name> with `--last` flag shows no taskrun found associated with ClusterTask <name>
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", 
  GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", 
  GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", 
  GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", 
  GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}  
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  $ tkn version
  Client version: 0.17.0
  Pipeline version: v0.22.0
  ```

- Operating System:

  ```
  All
  ```

# Expected Behavior

When doing a `tkn clustertask start` using `--last` flag a taskrun should be created which should use the values from the last run taskrun

```
$ tkn ct start yaml-lint -L
TaskRun started: yaml-lint-run-nxlmb

In order to track the TaskRun progress run:
tkn taskrun logs yaml-lint-run-nxlmb -f -n default
```

# Actual Behavior

When doing a `tkn clustertask start` using `--last` flag a taskrun it is showing no taskrun found associated to that clustertask

```
$ tkn ct start yaml-lint -L
Error: no TaskRuns related to ClusterTask yaml-lint found in namespace default
```

# Steps to Reproduce the Problem

1. Create a ClusterTask
2. Start a ClusterTask by creating a TaskRun
3. Now restart the ClusterTask using `tkn ct start` and using the flag `--last` or `-L`

# Additional Info
Since https://github.com/tektoncd/pipeline/pull/3764 got merged so only `tekton.dev/clusterTask` would be present when a taskrun is created for a clustertask

/assign

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

`tkn clustertask start` command with `--last` flag was checking for the
label `tekton.dev/task=name` in the created taskruns since any taskrun
created from clustertask had the labels `tekton.dev/clusterTask=name`
and `tekton.dev/task=name`.

Since pipelines 0.22 release the label `tekton.dev/task=name` has been
removed from the taskruns which were created from clustertasks.
See: https://github.com/tektoncd/pipeline/pull/3764

Fixing this in pkg/task/tasklastrun.go and adding corresponding tests.

Closes #1331 

Signed-off-by: vinamra28 <vinjain@redhat.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by vinamra28** [comment]
> /hold This will break backward compatibility. should we handle it better if possible

It would be compatible since since the TaskRun created from ClusterTask would still have both the labels
```
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines
 app.kubernetes.io/version=0.1
 hub.tekton.dev/catalog=tekton
 tekton.dev/clusterTask=yaml-lint
 tekton.dev/task=yaml-lint
```

File: pkg/task/tasklastrun.go [hunk 1]
```diff
@@ -37,11 +44,11 @@ func LastRun(cs *cli.Clients, task string, ns, kind string) (*v1beta1.TaskRun, e
 		return nil, err
 	}
 
-	// this is required as the same label is getting added for both task and ClusterTask
+	// this is required as the same label is getting added for both Task and ClusterTask
 	runs.Items = FilterByRef(runs.Items, kind)
```
Comment (piyush-garg) [inline pkg/task/tasklastrun.go:48]: Do we still need this then ?

**Comment by piyush-garg** [comment]
> > /hold This will break backward compatibility. should we handle it better if possible
> 
> It would be compatible since since the TaskRun created from ClusterTask would still have both the labels
> 
> ```
> Labels:
>  app.kubernetes.io/managed-by=tekton-pipelines
>  app.kubernetes.io/version=0.1
>  hub.tekton.dev/catalog=tekton
>  tekton.dev/clusterTask=yaml-lint
>  tekton.dev/task=yaml-lint
> ```

Aah right, I think it will break on the old version something around 0.11 and 0.12. I don't think we should support that much old version cc @tektoncd/cli-maintainers

File: pkg/task/tasklastrun.go (hunk 1 above)
Comment (vinamra28) [reply pkg/task/tasklastrun.go:48]: right....will remove it

**Review by vdemeester — APPROVED** [review]
/meow
