### PR TITLE
Fix resource creation failure in case of multiple

### LINKED ISSUE #456: Pipeline start creates only one resource
The following pipeline has 2 resources one of type git and another image but the start flow skips the image resource and starts the pipeline immediately after creating the git resource, which causes the pipelinerun to fail with missing resources:

```
$ tkn pipeline start petclinic-s2i-pipeline
no pipeline resource of type "git" found in namespace: pipelines-demo
please create new "git" resource
? Enter a name for a pipeline resource : petclinic-git
? Enter a value for url :  https://github.com/spring-projects/spring-petclinic
? Enter a value for revision :
New git resource "petclinic-git" has been created
resource status {}

Pipelinerun started: petclinic-s2i-pipeline-run-5bkp4
Showing logs...
PipelineRun pipelines-demo/petclinic-s2i-pipeline-run-5bkp4 doesn't bind Pipeline pipelines-demo/petclinic-s2i-pipeline's PipelineResources correctly: PipelineRun bound resources didn't match Pipeline: Didn't provide required values: [app-image]
```

### PR DESCRIPTION
**Pull request by piyush-garg**
This will fix the issue of resource creation
failure in case of creating multiple
resources on fly while executing
tkn pipeline start command

Add tests

fix #456

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [x] Run the code checkers with `make check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

File: pkg/cmd/pipeline/start_test.go [hunk 1]
```diff
@@ -1417,6 +1417,144 @@ func Test_start_pipeline_newGitRes_noExistingRes(t *testing.T) {
 	}
 }
 
+func Test_start_pipeline_newMultipleRes_noExistingRes(t *testing.T) {
```
Comment (pradeepitm12) [inline pkg/cmd/pipeline/start_test.go]: Thanks, @piyush-garg.
It would be really nice to have one more test with two different types of resource could be `git` and `image`.
