### PR TITLE
Fix custom output on describe commands

### LINKED ISSUE #640: Output and template flags on describe commands don't work
What is the purpose of the `-o` and `--template` flags do on `describe` commands? They don't seem to do anything currently:

```
$ tkn pr describe petclinic-run-pnlsl -o yaml

Name:           petclinic-run-pnlsl
Namespace:      demo
Pipeline Ref:   maven-build

Status
STARTED          DURATION    STATUS
27 minutes ago   8 minutes   Succeeded

Resources
NAME      RESOURCE REF
app-git

Params
No params

Taskruns
NAME                                   TASK NAME    STARTED          DURATION     STATUS
petclinic-run-pnlsl-gen-report-j64fv   gen-report   22 minutes ago   3 minutes    Succeeded
petclinic-run-pnlsl-int-test-8jslf     int-test     22 minutes ago   49 seconds   Succeeded
petclinic-run-pnlsl-build-5xqpb        build        27 minutes ago   4 minutes    Succeeded
```

### PR DESCRIPTION
**Pull request by chmouel**
Close #640

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [] Regenerate the manpages and docs with `make docs` and `make man` if needed.
- [X] Run the code checkers with `make check`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
describe command properly output with the -o switch to json or yaml
```

### CODE REVIEW

File: pkg/cmd/clustertask/describe.go [hunk 1]
```diff
@@ -134,6 +139,20 @@ or
 				Err: cmd.OutOrStderr(),
 			}
 
+			if err := validate.NamespaceExists(p); err != nil {
```
Comment (vdemeester) [inline pkg/cmd/clustertask/describe.go]: `ClusterTask` do not require a `namespace` :angel:

Comment (danielhelfand) [reply pkg/cmd/clustertask/describe.go]: Yes, this was taken out in #547
