### PR TITLE
pkg/suggestions: print help and error out 🏢

### LINKED ISSUE #1114: tkn shows only help message and does not throw error for some invalid sub-command
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b3b92b2", GitCommit:"b3b92b2", GitTreeState:"clean", BuildDate:"2020-07-15T09:27:21Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+012b3ec", GitCommit:"012b3ec", GitTreeState:"clean", BuildDate:"2020-07-24T07:23:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  $ tkn version
  Client version: 0.11.0
  Pipeline version: v0.14.3
  Triggers version: v0.6.1

  ```

- Operating System:

  ```
  Linux
  ```

# Expected Behavior
`tkn` should throw error along with help message

# Actual Behavior
`tkn` command only shows the help message

# Steps to Reproduce the Problem

1. Run `tkn ctl start some-task`
2. check the error code using `echo $?`

# Additional Info
Command logs
```
$ tkn ctl start some-task
CLI for tekton pipelines

Usage:
tkn [flags]
  tkn [command]

Available Commands:
  clustertask           Manage ClusterTasks
  clustertriggerbinding Manage clustertriggerbindings
  condition             Manage conditions
  eventlistener         Manage eventlisteners
  pipeline              Manage pipelines
  pipelinerun           Manage PipelineRuns
  resource              Manage pipeline resources
  task                  Manage Tasks
  taskrun               Manage TaskRuns
  triggerbinding        Manage triggerbindings
  triggertemplate       Manage triggertemplates

Other Commands:
  completion            Prints shell completion scripts
  version               Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.
$ 
$ echo $?
0

```
Command logs for `tkn` catalog task
```
$ tkn ct ls | grep tkn
tkn                        This task performs ...   2 days ago

$ tkn ct start tkn -p ARGS=ctl,start,some-task --showlog
TaskRun started: tkn-run-k44rn
Waiting for logs to be available...
[tkn] CLI for tekton pipelines
[tkn] 
[tkn] Usage:
[tkn] tkn [flags]
[tkn]   tkn [command]
[tkn] 
[tkn] Available Commands:
[tkn]   clustertask           Manage ClusterTasks
[tkn]   clustertriggerbinding Manage clustertriggerbindings
[tkn]   condition             Manage conditions
[tkn]   eventlistener         Manage eventlisteners
[tkn]   pipeline              Manage pipelines
[tkn]   pipelinerun           Manage PipelineRuns
[tkn]   resource              Manage pipeline resources
[tkn]   task                  Manage Tasks
[tkn]   taskrun               Manage TaskRuns
[tkn]   triggerbinding        Manage triggerbindings
[tkn]   triggertemplate       Manage triggertemplates
[tkn] 
[tkn] Other Commands:
[tkn]   completion            Prints shell completion scripts
[tkn]   version               Prints version information
[tkn] 
[tkn] Flags:
[tkn]   -h, --help   help for tkn
[tkn] 
[tkn] Use "tkn [command] --help" for more information about a command.

$ 
$ tkn tr ls 
NAME                                      STARTED          DURATION      STATUS
tkn-run-k44rn                             30 seconds ago   -11 seconds   Succeeded
```

**Impact**:
1. If the user uses tkn catalog task (https://github.com/tektoncd/catalog/blob/master/task/tkn/0.1/tkn.yaml) and by mistake if he provides invalid args the taskrun status will be shown as `Succeeded`.
2. If user has written any script to run `tkn` commands and uses some invalid subcommand he will not get to know if the command succeeded or not

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

In case of "suggestion", we want to print help and error out, as this
means the subcommand does not exists.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Fixes #1114 
/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Run the code checkers with `make check`
- [x] Regenerate the manpages, docs and go formatting with `make generated`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Invalid subcommands now return an error (exitCode > 0) even in case of proposed suggestions
```

### CODE REVIEW

**Comment by vinamra28** [comment]
Thanks for fixing this :sweat_smile:. Can we error out the help message like this ?
```
$ ./tkn
Error: tkn doesn't exists
CLI for tekton pipelines

Usage:
tkn [flags]
  tkn [command]

Available Commands:
  clustertask           Manage ClusterTasks
  clustertriggerbinding Manage clustertriggerbindings
  condition             Manage conditions
  eventlistener         Manage eventlisteners
  pipeline              Manage pipelines
  pipelinerun           Manage PipelineRuns
  resource              Manage pipeline resources
  task                  Manage Tasks
  taskrun               Manage TaskRuns
  triggerbinding        Manage triggerbindings
  triggertemplate       Manage triggertemplates

Other Commands:
  completion            Prints shell completion scripts
  version               Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.
```

**Comment by danielhelfand** [comment]
An issue with this I noticed is that running `tkn` results in an error saying: `Error: tkn  doesn't exists`. Just running the root command on its own should result in displaying the help message.

With change:

```
CLI for tekton pipelines

Usage:
tkn [flags]
  tkn [command]

Available Commands:
  clustertask           Manage ClusterTasks
  clustertriggerbinding Manage clustertriggerbindings
  condition             Manage conditions
  eventlistener         Manage eventlisteners
  pipeline              Manage pipelines
  pipelinerun           Manage PipelineRuns
  resource              Manage pipeline resources
  task                  Manage Tasks
  taskrun               Manage TaskRuns
  triggerbinding        Manage triggerbindings
  triggertemplate       Manage triggertemplates

Other Commands:
  completion            Prints shell completion scripts
  version               Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.
Error: tkn  doesn't exists
```

Should be:

```
CLI for tekton pipelines

Usage:
tkn [flags]
  tkn [command]

Available Commands:
  clustertask           Manage ClusterTasks
  clustertriggerbinding Manage clustertriggerbindings
  condition             Manage conditions
  eventlistener         Manage eventlisteners
  pipeline              Manage pipelines
  pipelinerun           Manage PipelineRuns
  resource              Manage pipeline resources
  task                  Manage Tasks
  taskrun               Manage TaskRuns
  triggerbinding        Manage triggerbindings
  triggertemplate       Manage triggertemplates

Other Commands:
  completion            Prints shell completion scripts
  version               Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.
```

**Comment by vdemeester** [comment]
@vinamra28 @danielhelfand should be fixed :angel:

File: pkg/suggestion/suggest.go [hunk 1]
```diff
@@ -74,7 +74,11 @@ func SubcommandsRequiredWithSuggestions(cmd *cobra.Command, args []string) error
 		return fmt.Errorf(requireMsg, typedName, cmd.CommandPath())
 	}
 
-	return cmd.Help()
+	if typedName == "" {
+		return cmd.Help()
+	}
+	fmt.Fprintf(cmd.ErrOrStderr(), "%s %s doesn't exists\n", cmd.Name(), typedName)
```
Comment (danielhelfand) [inline pkg/suggestion/suggest.go:80]: @vdemeester @vinamra28 

So with this approach we get the following:

```
./tkn ctl
tkn ctl doesn't exists
CLI for tekton pipelines

Usage:
tkn [flags]
  tkn [command]

Available Commands:
  clustertask           Manage ClusterTasks
  clustertriggerbinding Manage clustertriggerbindings
  condition             Manage conditions
  eventlistener         Manage eventlisteners
  pipeline              Manage pipelines
  pipelinerun           Manage PipelineRuns
  resource              Manage pipeline resources
  task                  Manage Tasks
  taskrun               Manage TaskRuns
  triggerbinding        Manage triggerbindings
  triggertemplate       Manage triggertemplates

Other Commands:
  completion            Prints shell completion scripts
  version               Prints version information

Flags:
  -h, --help   help for tkn

Use "tkn [command] --help" for more information about a command.
```

1. This is difficult to find when located at the top because of the displaying of the help message.
2. It is difficult to find the error message since there is no `Error` prefix. 

I think an ideal solution to this would be as follows:

```
$ tkn ctl

Error: command "ctl" does not exist. Run tkn help for list of available commands.
```

Comment (vdemeester) [reply pkg/suggestion/suggest.go:80]: @danielhelfand while still showing the help right ?

Comment (danielhelfand) [reply pkg/suggestion/suggest.go:80]: Without. I think something like this would make it easier to find the error:

```go
return fmt.Errorf("command %s %s doesn't exist. Run tkn help for available commands", cmd.Name(), typedName)
```

Would result in:
```
$ tkn ctl
Error: command tkn ctl doesn't exist. Run tkn help for available commands
```

Comment (vdemeester) [reply pkg/suggestion/suggest.go:80]: Alright, make sense too :upside_down_face:
