### PR TITLE
Checked existence of resources before deletion

### LINKED ISSUE #1480: tkn pr/tr/* delete always ask for confirmation to delete
# Versions and Operating System

latest version of cli compiled from main branch

# Expected Behavior

not asking everytime to delete object even if it doesn't exist

# Actual Behavior

asking everytime to delete object

# Steps to Reproduce the Problem

1. `tkn p delete heraldsantibodyskickoffs`
2. `tkn t delete FORTRANgoobersnotified`
3. `tkn ct delete dailysdenhashs`

# Additional Info

You can generate random words with https://github.com/chmouel/chmouzies/blob/master/misc/randomword :D

### PR DESCRIPTION
**Pull request by mansi103**
Earlier there was a prompt that appeared for deletion before checking
whether the resource exist or not in the cluster. With this PR we are
handling the same.

Signed-off-by: mansi103 <mansiagarwal103@gmail.com>

Fix #1480

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Checked existence of resources before deletion
```

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Comment by vinamra28** [comment]
closes #1480

**Comment by pradeepitm12** [comment]
Hey, @mansi103 Thanks for the PR.
I was wondering what will happen if the user tries to delete two clustertasks like  `tkn ct delete ctA ctB`
But ctB is not available.
With the current approach, it will give error like 
``` 
./tkn ct delete ctA ctB
Error: clustertasks.tekton.dev "ctB" not found
```
And will not delete any of the given clustertasks regardless they are available or not.
How about deleting the available ones and printing error for the not found ones.
```
tkn ct delete ctA ctB ctC
ClusterTasks deleted: "ctA"
ClusterTasks deleted: "ctB"
Error from server (NotFound): clustertasks.tekton.dev "ctC" not found

```
@piyush-garg @vinamra28  What do you think^^

**Comment by vdemeester** [comment]
> How about deleting the available ones and printing error for the not found ones.

That's how `docker` cli does, so I am 💯% with @pradeepitm12 on this 👍🏼

**Comment by vinamra28** [comment]
@mansi103 can you please try to repush? It seems that easycla isn't happy :sweat_smile:

File: pkg/cmd/clustertask/delete_test.go [hunk 1]
```diff
@@ -296,6 +296,15 @@ func TestClusterTaskDelete(t *testing.T) {
...
 			want:        "must provide ClusterTask name(s) or use --all flag with delete",
 		},
+		{
+			name:        "Delete the ClusterTask present and give error for non-existent ClusterTask",
+			command:     []string{"delete", "nonexistent", "tomatoes2"},
+			dynamic:     seeds[5].dynamicClient,
+			input:       seeds[5].pipelineClient,
+			inputStream: nil,
+			wantError:   true,
+			want:        "failed to delete ClusterTask \"nonexistent\": clustertasks.tekton.dev \"nonexistent\" not found",
```
Comment (piyush-garg) [inline pkg/cmd/clustertask/delete_test.go:306]: You are asserting the error here, but should also assert the other tasks that got deleted

File: pkg/cmd/clustertask/delete.go [hunk 2]
```diff
@@ -25,11 +25,30 @@ import (
 	"github.com/tektoncd/cli/pkg/formatted"
 	"github.com/tektoncd/cli/pkg/options"
 	trlist "github.com/tektoncd/cli/pkg/taskrun/list"
+	"go.uber.org/multierr"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/apimachinery/pkg/runtime/schema"
 	cliopts "k8s.io/cli-runtime/pkg/genericclioptions"
 )
 
+// ctExists validates that the first argument is a valid clustertask name
```
Comment (piyush-garg) [inline pkg/cmd/clustertask/delete.go:34]: this is confusing, it is validating all args not first

File: pkg/cmd/clustertask/delete.go [hunk 3]
```diff
@@ -25,11 +25,30 @@ import (
...
+
+	c, err := p.Clients()
+	if err != nil {
+		return err
+	}
+	var errorList error
+	for _, name := range args {
+		_, err := clustertask.Get(c, name, metav1.GetOptions{})
+		if err == nil {
+			return nil
```
Comment (piyush-garg) [inline pkg/cmd/clustertask/delete.go:45]: Why `return nil` here. should we not iterate on further ct

Comment (piyush-garg) [reply pkg/cmd/clustertask/delete.go:45]: You can do

```
if err != nil {
    errorList = multierr.Append(errorList, err)
}
```

**Comment by piyush-garg** [comment]
Assume the tkn ct is available in the cluster, and foobar not available

The current output in PR is
```
./tkn ct delete foobar tkn
Are you sure you want to delete ClusterTask(s) "foobar", "tkn" (y/n): y
ClusterTasks deleted: "tkn"
Error: failed to delete ClusterTask "foobar": clustertasks.tekton.dev "foobar" not found
```

Should not the output be like
```
./tkn ct delete foobar tkn
Error: failed to delete ClusterTask "foobar": clustertasks.tekton.dev "foobar" not found
Are you sure you want to delete ClusterTask(s) "tkn" (y/n): y
ClusterTasks deleted: "tkn"
```

cc @pradeepitm12 @vinamra28 @vdemeester

**Comment by vdemeester** [comment]
@piyush-garg I think the later is better, but I don't have strong opinion 😛

**Comment by chmouel** [comment]
i like the later better :)

**Comment by piyush-garg** [comment]
> @piyush-garg I think the later is better, but I don't have strong opinion stuck_out_tongue

The main difference is, if we are checking for resource existence first, then we should not ask for the resource which does not exist in prompt question then @vdemeester

**Comment by mansi103** [comment]
Thanks for all the reviews. I have updated the PR. PTAL.
/cc @vdemeester @pradeepitm12 @piyush-garg @vinamra28

**Comment by vinamra28** [comment]
The PR now looks like 
```
$ tkn ct delete git-clone notfound
Are you sure you want to delete ClusterTask(s) "git-clone" (y/n): y
ClusterTasks deleted: "git-clone"
Error: clustertasks.tekton.dev "notfound" not found
```
and
```
$ tkn ct delete notfound not
Error: clustertasks.tekton.dev "notfound" not found; clustertasks.tekton.dev "not" not found
```
cc @piyush-garg @chmouel @vdemeester @pradeepitm12

**Comment by pradeepitm12** [comment]
/LGTM
let's get one more and then we are good to go.

File: pkg/cmd/clustertask/delete.go [hunk 4]
```diff
@@ -60,11 +81,19 @@ or
 				Err: cmd.OutOrStderr(),
 			}
 
-			if err := opts.CheckOptions(s, args, ""); err != nil {
+			availableCts, errs := ctExists(args, p)
```
Comment (piyush-garg) [inline pkg/cmd/clustertask/delete.go:84]: cant we just print the error of non-existent one here

because in the end if somehow the delete call caused an error in deleting, these errors will be missed.

Comment (mansi103) [reply pkg/cmd/clustertask/delete.go:84]: @piyush-garg I tried to make it similar to how kubectl does. Moreover, I tried the approach which you said but in that case it wasn't returning the error.

> because in the end if somehow the delete call caused an error in deleting, these errors will be missed.

🤔 I am unable to visualize any such. Can you please help me here :sweat_smile:. Moreover, I think if somebody doesn't have permission to delete a resource from cluster then that error message which should be displayed first showing `not able to delete` instead of first showing that `resource not found`. WDYT?

Comment (piyush-garg) [reply pkg/cmd/clustertask/delete.go:84]: there can be scenario like user have read right, not write rights. So in first check there will be no error

Comment (mansi103) [reply pkg/cmd/clustertask/delete.go:84]: In think in this case letting the user know that they won't be able to delete is a better idea instead of first letting them know that a particular resource is not found and then showing the error of won't be able to delete because it will not be a proper UX. 
cc: @piyush-garg @chmouel @vdemeester @vinamra28

**Review by chmouel — COMMENTED** [review]
/lgtm
